[package]
name = "chip8"
version = "0.1.0"
authors = ["Andreas Arvidsson <andreas.arvidson@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
ggez = "0.5.0-rc.2"
nalgebra = "0.18"
num-traits = "0.2.5"
num-derive = "0.2.5"